runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT main:app
handlers:
        - url: .*
          script: main.app
runtime_config:
  python_version: 3
  
resources:
  memory_gb: 4.0
